# Generated by Django 5.2.13 on 2026-04-12 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2048)),
                ('platform', models.CharField(choices=[('youtube', 'YouTube'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('media_type', models.CharField(choices=[('video', 'Video'), ('image', 'Image'), ('reel', 'Reel'), ('audio', 'Audio')], default='video', max_length=10)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('thumbnail', models.URLField(blank=True, max_length=2048)),
                ('file_path', models.CharField(blank=True, max_length=1000)),
                ('file_size', models.BigIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('duration', models.CharField(blank=True, max_length=20)),
                ('quality', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
