# Generated by Django 5.2.13 on 2026-04-15 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadhistory',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='downloadhistory',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
